//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWebMobi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int employeeId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public byte[] profilephoto { get; set; }
        public int departmentId { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> modifyBy { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
